// <auto-generated />
using System;
using MEkroth.Matrix.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MEkroth.Matrix.Api.Migrations
{
    [DbContext(typeof(SqlLiteApplicationDbContext))]
    partial class SqlLiteApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("MEkroth.Matrix.Api.StatusMatrices.StatusMatrix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Statuses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusMatrices");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd69b7db-dd45-44ff-85f4-6d4fe1bf75ff"),
                            Name = "Status Matrix 1",
                            Statuses = "[0,3,1,0,1,3,2,0,3,3,1,0,3,3,1,2,0,1,0,3,3,0,0,2,3]"
                        },
                        new
                        {
                            Id = new Guid("45b48626-b2a8-4e28-a28d-a5631db95a95"),
                            Name = "Status Matrix 2",
                            Statuses = "[2,1,1,1,2,3,3,2,3,2,3,1,3,1,0,0,2,3,2,1,2,0,3,2,1]"
                        },
                        new
                        {
                            Id = new Guid("930a4377-7cb4-4c59-805a-9bd4ae77aabc"),
                            Name = "Status Matrix 3",
                            Statuses = "[2,0,0,0,0,2,2,0,2,0,2,3,2,2,3,1,3,1,1,0,2,2,1,0,0]"
                        },
                        new
                        {
                            Id = new Guid("9874769a-9a34-45c7-9eab-6064e2fe1ed6"),
                            Name = "Status Matrix 4",
                            Statuses = "[0,0,0,2,2,2,3,3,0,3,2,2,0,0,3,1,2,2,2,0,1,3,0,1,2]"
                        },
                        new
                        {
                            Id = new Guid("e953eee8-b778-4abb-8867-52b47f858e92"),
                            Name = "Status Matrix 5",
                            Statuses = "[2,2,3,3,2,0,2,0,2,3,3,2,3,1,0,0,3,3,3,2,0,1,0,3,0]"
                        },
                        new
                        {
                            Id = new Guid("9b520ce2-a36d-437f-a5c9-49f31bf34045"),
                            Name = "Status Matrix 6",
                            Statuses = "[3,1,1,3,1,3,3,3,1,3,1,3,3,3,2,1,2,2,2,3,3,3,1,2,0]"
                        },
                        new
                        {
                            Id = new Guid("c135365b-892d-4783-814a-5bb1ced2f5cf"),
                            Name = "Status Matrix 7",
                            Statuses = "[0,0,0,1,0,2,0,0,3,2,1,1,0,0,3,3,1,1,1,2,0,3,3,1,2]"
                        },
                        new
                        {
                            Id = new Guid("688d4e6b-7c46-443c-8a82-2d37383e0747"),
                            Name = "Status Matrix 8",
                            Statuses = "[1,0,2,2,1,3,3,3,2,3,2,2,2,2,1,3,0,1,1,2,2,3,3,2,0]"
                        },
                        new
                        {
                            Id = new Guid("5712ef61-14fc-4032-b58c-ed5a7f02087d"),
                            Name = "Status Matrix 9",
                            Statuses = "[3,3,3,1,2,2,2,2,1,2,2,2,3,0,3,1,2,3,2,1,1,2,2,1,3]"
                        },
                        new
                        {
                            Id = new Guid("d032d211-0868-4d26-815e-11ff1a6ae6b7"),
                            Name = "Status Matrix 10",
                            Statuses = "[2,1,2,0,3,2,2,3,2,0,3,1,0,2,1,0,2,1,3,0,1,2,3,3,1]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
